name: Artisans Development WorkFlow

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  POSTGRES_USER: artisans
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: artisans_ci

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres_db:
        image: postgres
        env:
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_DB: $POSTGRES_DB
        ports:
          - 5432:5432
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup and Install Node.Js
        uses: actions/setup-node@v3.4.1
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install project dependencies
        run: yarn install --frozen-lockfile
      - name: Run Tests
        run: yarn run test
      - name: Lint Code
        run: yarn run lint

  # Would be used for deployment
  # build:
  #   runs-on: ubuntu-latest
  #   needs: ['lint']

  # Would be added later
  # Deploy:
  # runs-on: ubuntu-latest
